### ISSUE TITLE
Update Redirects

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/linnullmann#6]
We’ve recently fixed a bug in Netlify’s redirect handling, and we’ve identified one or more redirect rules on www.linnullmann.no that will begin to behave differently after the bug fix is applied on April 7th.

For more information on the nature of the bug and how it affects redirect rules, please visit the Community topic on our fix for forced redirects and shadowing behavior.

The redirect rules listed below are currently behaving as forced redirects (redirecting past existing content), even though you haven’t explicitly configured them to do so. You may want to check each redirect to be sure you want to continue this behavior, and if so, explicitly mark the rule as forced. In a _redirects file, you can do this by adding ! to the redirect status code. In a netlify.toml file, add the key and value force=true.

The following redirect rules might be affected by this change:

/en/books/de-urolige/ ... /en/books/unquiet/ 301 ...

**Comment by regisphilibert** [comment]
One alias, but the origin does not exist, so no need to change anything.
